version: 0.0.1
application:
  start: []
  end: []
  listeners: []
domain:
  version: 0.0.1
  enums: []
  entities:
    - name: CountryLanguages
      intermediate: true
      primaryKey:
        - id
      properties:
        - name: id
          type: integer
          required: true
          autoIncrement: true
        - name: languageCode
          type: string
          length: 4
          required: true
        - name: countryName
          type: string
          length: 32
          required: true
      uniqueKey:
        - countryName
        - languageCode
      required: []
      indexes: []
      relations:
        - name: country
          type: oneToMany
          from: countryName
          entity: Country
          to: name
          target: countryLanguages
        - name: languages
          type: oneToMany
          from: languageCode
          entity: Languages
          to: code
          target: countryLanguages
      dependents: []
    - name: Languages
      primaryKey:
        - code
      properties:
        - name: code
          type: string
          required: true
          length: 4
        - name: name
          type: string
          required: true
          length: 16
      uniqueKey: []
      required: []
      indexes: []
      relations: []
      dependents: []
    - name: Region
      primaryKey:
        - code
      properties:
        - name: code
          type: string
          required: true
          length: 2
        - name: name
          type: string
          required: true
          length: 32
      uniqueKey: []
      required: []
      indexes: []
      relations: []
      dependents: []
    - name: Pos
      primaryKey:
        - lat
      properties:
        - name: lat
          type: decimal
          required: true
        - name: log
          type: decimal
          required: true
      uniqueKey:
        - log
      required: []
      indexes: []
      relations: []
      dependents: []
    - name: Timezones
      primaryKey:
        - name
      properties:
        - name: name
          type: string
          required: true
          length: 32
        - name: offset
          type: integer
          required: false
        - name: posLat
          type: decimal
          required: true
        - name: countryName
          type: string
          required: true
      uniqueKey: []
      required: []
      indexes: []
      relations:
        - name: pos
          type: oneToMany
          from: posLat
          entity: Pos
          to: lat
        - name: country
          type: oneToMany
          from: countryName
          entity: Country
          to: name
          target: timezones
      dependents: []
    - name: Country
      primaryKey:
        - name
      properties:
        - name: name
          type: string
          required: true
          length: 32
        - name: phoneCode
          type: integer
          required: true
        - name: priority
          type: integer
          required: true
        - name: regionCode
          type: string
          required: true
          length: 2
      uniqueKey:
        - phoneCode
      required: []
      indexes: []
      relations:
        - name: region
          type: oneToMany
          from: regionCode
          entity: Region
          to: code
      dependents: []
infrastructure:
  paths:
    src: src
    data: data
    domain: domain
  mappings: []
  sources: []
  stages: []
  views: []
