version: 0.0.1
application:
  start: []
  end: []
  listeners: []
domain:
  version: 0.0.1
  enums: []
  entities:
    - name: CountriesLanguages
      intermediate: true
      primaryKey:
        - id
      properties:
        - name: id
          type: integer
          required: true
          autoIncrement: true
        - name: languageCode
          type: string
          length: 4
          required: true
        - name: countriesName
          type: string
          length: 32
          required: true
      uniqueKey:
        - countriesName
        - languageCode
      required: []
      indexes: []
      relations:
        - name: countries
          type: oneToMany
          from: countriesName
          entity: Countries
          to: name
          target: countriesLanguages
        - name: languages
          type: oneToMany
          from: languageCode
          entity: Languages
          to: code
          target: countriesLanguages
      dependents: []
    - name: Languages
      primaryKey:
        - code
      properties:
        - name: code
          type: string
          required: true
          length: 4
        - name: name
          type: string
          required: true
          length: 16
      uniqueKey: []
      required: []
      indexes: []
      relations: []
      dependents: []
    - name: Regions
      primaryKey:
        - code
      properties:
        - name: code
          type: string
          required: true
          length: 2
        - name: name
          type: string
          required: true
          length: 32
      uniqueKey: []
      required: []
      indexes: []
      relations: []
      dependents: []
    - name: Positions
      primaryKey:
        - lat
      properties:
        - name: lat
          type: decimal
          required: true
        - name: long
          type: decimal
          required: true
      uniqueKey:
        - long
      required: []
      indexes: []
      relations: []
      dependents: []
    - name: Timezones
      primaryKey:
        - name
      properties:
        - name: name
          type: string
          required: true
          length: 32
        - name: offset
          type: integer
          required: false
        - name: positionLat
          type: decimal
          required: true
        - name: countriesName
          type: string
          required: true
      uniqueKey: []
      required: []
      indexes: []
      relations:
        - name: position
          type: oneToMany
          from: positionLat
          entity: Positions
          to: lat
        - name: countries
          type: oneToMany
          from: countriesName
          entity: Countries
          to: name
          target: timezones
      dependents: []
    - name: Countries
      primaryKey:
        - name
      properties:
        - name: name
          type: string
          required: true
          length: 32
        - name: phoneCode
          type: integer
          required: true
        - name: priority
          type: integer
          required: true
        - name: regionCode
          type: string
          required: true
          length: 2
      uniqueKey:
        - phoneCode
      required: []
      indexes: []
      relations:
        - name: region
          type: oneToMany
          from: regionCode
          entity: Regions
          to: code
      dependents: []
infrastructure:
  paths:
    src: src
    data: data
    domain: domain
  mappings: []
  sources: []
  stages: []
  views: []
